# 创建一个zero2prod的桥接网络
networks:
  next-dashboard:
    driver: bridge

services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    restart: always
    ports:
      - '5432:5432'
    environment:
      # 数据库基本信息
      TZ: Asia/Shanghai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: next_dashboard
      # 指定数据目录（可选，容器默认也是 /var/lib/postgresql/data）
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      # 数据持久化
      - ../postgresql/data/:/var/lib/postgresql/data/
      # 日志持久化（容器内写入 /var/log/postgresql/postgresql.log）
      - ../postgresql/logs/:/var/log/postgresql/
      # 自定义主配置文件
      - ./postgresql/conf/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      # 自定义访问控制文件
      - ./postgresql/conf/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
    # 使用自定义配置文件启动 Postgres
    command: [
      "postgres",
      "-c", "config_file=/etc/postgresql/postgresql.conf"
    ]
    networks:
      - next-dashboard

